FROM jupyter/datascience-notebook

COPY requirements-dev.txt /tmp/

RUN pip install --upgrade pip setuptools wheel \
    && pip install -r /tmp/requirements-dev.txt \
    && fix-permissions $CONDA_DIR \
    && fix-permissions /home/$NB_USER



COPY . /home/$NB_USER

USER root

RUN python setup.py sdist bdist_wheel \
    && pip install /home/$NB_USER \
    # Uninstall dwdbulk so that there are no namespace conflicts with source files.
    && pip uninstall -y dwdbulk \
    && fix-permissions $CONDA_DIR \
    && fix-permissions /home/$NB_USER

USER $NB_UID
